language: node_js
node_js:
  - "6"
  - "8"
  - "10"
  - "12"

# Use faster Docker architecture on Travis.
sudo: false
before_script: yarn config set ignore-engines true 
script: yarn test
# TODO: coverage
# after_success: npm run coveralls

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/dd893be75c6b9908987d
    on_success: change
    on_failure: always
    on_start:   never
